baseURL: 'http://localhost:1313/'
title: "WZH 的博客"
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: '一个专注于阅读与技术分享的个人博客'
homepage: 'http://localhost:1313/'
defaultContentLanguage: 'zh'
enableRobotsTXT: true
paginate: 10
hasCJKLanguage: true
copyright: "2026 WZH All rights reserved"
markup:
  goldmark:
    extensions:
      passthrough:
        enable: true
        delimiters:
          block: [['$$', '$$']]
          inline: [['$', '$']]
Author:
  name: "wzh"
  email: ""
params:
  brand: HOME
  avatarURL: images/avatar-eyes.png
  author: wzh
  authorDescription: 记录技术学习、工具分享与个人思考
  info: 一个分享技术文章、效率工具与个人见解的博客
  favicon: images/avatar.png
  mainSections:
    - blog
    - art
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: false
    showMetaTags: true
  darkModeTheme: data-dark-mode
  #darkModeTheme: icy-dark-mode
  comments:
    giscus:
      enable: true
      repo: wangzh12023/blog
      repo_id: R_kgDOT8Xh4A
      category: Announcements
      category_id: DIC_kwDOT8Xh4M4DDpPe
      mapping: pathname
      position: top
      lang: zh-CN
  analytics:
    google:
      SiteVerificationTag: xxx
    umami:
      enable: false
      website_id: xxx
      url: ''
  guestbook:
    title: 留言板
    description: 您的评论，会让该网站更精彩！
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/wangzh12023'
menu:
  main:
    - name: 文章
      url: /blog
      weight: 1
    - name: 随笔
      url: /art
      weight: 2
    - name: 分类
      url: /tags
      weight: 3
    - name: Archive
      url: /archives
      weight: 4
taxonomies:
  series: series
  tag: tags
